import os
import sys
from datetime import datetime

import pandas as pd
from bs4 import BeautifulSoup

from lib.combine_textboxes import extract_textboxes

if len(sys.argv) != 4:
    print('''Usage: python xmldir_to_db.py XML_FILES_DIR OUTPUT_DB OUTPUT_TABLE

This program parses the XML files generated by pdf2txt.py into text boxes, and saves the result to a database.

All of the .xml files in XML_FILES_DIR are assumed to be parseable output from earlier stages of this process.
For example, we are assuming that the deepest directory in XML_FILES_DIR is the date of the newspaper,
and that the filename is expected to be the slug of the newspaper before the first period.

OUTPUT_DB is expected to be a sqlalchemy URI.
The output database is appended to, so subsequent runs of the same command will create duplicates.''')
    sys.exit(1)

XML_FILES_DIR, SQLALCHEMY_URI, OUTPUT_TABLE = sys.argv[1:]

date = datetime.strptime(os.path.basename(os.path.abspath(XML_FILES_DIR)), '%Y_%m_%d')

for i, dir_entry in enumerate(os.scandir(XML_FILES_DIR)):
    if i % 50 == 0:
        print('.', end='')
        sys.stdout.flush()

    fn = dir_entry.name
    if not fn.endswith('.xml'):
        continue
    
    slug = fn.split('.')[0]

    with open(os.path.join(XML_FILES_DIR, fn)) as f:
        soup = BeautifulSoup(f.read(), 'lxml')
        df = extract_textboxes(soup)

    if len(df) == 0:
        continue

    df['date'] = date
    df['slug'] = slug

    df.to_sql(OUTPUT_TABLE, SQLALCHEMY_URI, if_exists='append', index=False)
